# Default locale for UI strings
locale: "en"

# Customize UI strings
ui-strings:
  # display-help:         "Display help"
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # redo:                 "Redo"
  # ok:                   "Okay"
  # contact-intro:        "Contact: "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
 title:    "Here is my title."
 logo:     ""
 color:    "is-primary"
 subtitle: "A subtitle here, possibly with _markdown_ formatting."

# Website footer
footer:
 text:    "Some text here, possibly with **markdown** formatting."
 contact:  ""

# Allow users to send you emails with the summary?
mail-to:

# Display help along with questions by default?
display-help: true

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
display-score-details: true

# Only the score with the highest value?
display-score-top-result: true

# In a branch of the tree, should the target node be set depending on
# the updated value of conditional-score-outputs?
conditional-navigation: false

# Some text message to always display after the score results
display-unconditionnally: ""

# Set initial variables to register scores.  Each entry of
# score-variables start with the name of the variable (you can pick
# up any yaml-acceptable name), then:
#
# (1) "display": what to display when detailed scores are displayed
# (2) "value": the initial value of the variable
# (3) "as-top-result-display": what to display when the variable is
#      the one with the highest score when the user is done.
score-variables:
  score-1:
    display: "Score for 1"
    value: 0
    as-top-result-display: "1 wins :)"
  score-2:
    display: "Score for 2"
    value: 0
    max: 10
    as-top-result-display: "2 wins :("

# Set conditional output depending on scores.
# Each entry is composed of the name of the condition (you can pick up
# any yaml-acceptable name), then:
#
# (1) notification (optional): bulma-based class names for the UI notification
# (2) message (mandatory): message to display when one of the condition is met
# (3) anything else is a "condition", which lists variables and their minimal
# values for the condition to be met.
conditional-score-outputs:
  cas-1: # free-form
    notification: "is-success"
    priority: 1
    # Final score message supports using formatting strings for
    # scores.  Strings starting with "%" and matching a score name
    # will be interpolated: e.g. here the message will display the
    # value of "score-1".
    message: "1 wins! :)  Here is the score 1: %score-1"
    condition-1: #free-form
      # cas-1 is the case when score-& >= 1
      score-1: 1
  cas-2: # free-form
    notification: "is-danger"
    message: "2 wins! :(  Here is the score 2: %score-2"
    # When max is set as below, %score-2 above will be formatted as a
    # percentage: if score 2 is 10 and max is 10, the percent is 100.
    condition-1: #free-form
      # cas-2 is the case when score-2 >= 9
      score-2: 9

# Mandatory configuration option
tree:
  - node:       "0"
    text:       "A title for the default page"
    home-page:  true
    force-help: true
    no-summary: true
    help:       "Some introductory text here."
    choices:
    - answer: "Start now"
      goto:   "1"
      color:  "is-info"

  - node:       "1"
    progress:   "[1 3]"  # progress bar
    text:       "Is it the first question?"
    help:       "Some **help text** here for the first question.  Markdown formatting accepted."
    start-page: true
    choices:
    - answer:  "Yes"
      summary: "Yes, this is the first question."
      explain: "Some explanation here."
      score:
        score-1:
          value: 1
      goto:    "2"
      color:   "is-info"
    - answer:  "No"
      summary: "No, this is not the first question."
      color:   "is-warning"
      goto:    "end"

  - node:     "2"
    progress: "[2 3]"  # progress bar
    text:     "Is it the second question?"
    help:     "Some help text here for the second question."
    choices:
    - answer:  "Yes"
      summary: "Yes, this is the second question!"
      score:
        score-2:
          value: 10
      goto:    "3"
      color:   "is-info"
    - answer:  "No"
      summary: "No, this is not the second question."
      color:   "is-warning"
      goto:    "end"

  - node:     "3"
    progress: "[3 3]"  # progress bar
    text:     "Is it the _third_ question?"
    help:     "Some help text here for the second question."
    choices:
      - answer:  "Yes"
        summary: ["Yes, this is the third question...", "This will end soon, I promise."]
        goto: "end"
        color: "is-info"
      - answer:  "No"
        summary: "No, this is not the third question."
        color: "is-warning"
        goto: "end"

  - node: "end"
    text: "This is the end."
    done: true
